---
name: Extract TF resource IDs
on:
  pull_request_target:
    paths:
      - 'data/**'
    types: ['opened', 'edited']

jobs:
  extract-tf-resource-ids:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.21.3'

      - name: extract TF resource ids and update PR body
        run: |
          cd ./tools/extract-tf-resource-ids
          make run
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PANDORA_TOKEN }}
